#!/usr/bin/env node
// Generates src/version.ts from package.json so the SDK can render its own
// version in the UI without drifting from the published version. Runs as the
// first step of `bun run build`. The generated file IS committed (the .d.ts
// references it), but it is always overwritten on build, so package.json is
// the single source of truth.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const out = `// AUTO-GENERATED by scripts/gen-version.mjs — do not edit by hand.
// Source of truth: package.json "version". Regenerated on every build.
export const ELVIX_SDK_VERSION = ${JSON.stringify(pkg.version)};
`;
writeFileSync(join(root, "src", "react", "version.ts"), out);
console.log(`gen-version: wrote src/react/version.ts (ELVIX_SDK_VERSION = ${pkg.version})`);
