/**
 * Postbuild fixups:
 *
 *  1. tsup/esbuild strips the `"use client"` directive when bundling, which
 *     makes Next's App Router treat the React entry as a Server Component
 *     and crash on createContext. The react bundle is client-only (index.js
 *     is type-only, server.js is server-only), so we re-prepend the directive
 *     to dist/react.js after the build. Idempotent.
 *
 *  2. Ship a `dist/styles.css.d.ts` ambient declaration so strict-tsconfig
 *     consumers can `import "@elvix.is/sdk/styles.css"` without hand-rolling
 *     a globals.d.ts shim. Cycle-2 friction: install.md says "REQUIRED" for
 *     the stylesheet import but every Next + strict TS user got a TS2307
 *     until they wrote their own ambient module. Wired via the
 *     `exports["./styles.css"].types` field in package.json.
 */
import { readFileSync, writeFileSync } from "node:fs";

const file = "dist/react.js";
const src = readFileSync(file, "utf8");
const directive = '"use client";';

if (!src.startsWith(directive) && !src.startsWith("'use client'")) {
  writeFileSync(file, `${directive}\n${src}`);
  console.log(`postbuild: prepended "use client" to ${file}`);
} else {
  console.log(`postbuild: ${file} already has the client directive`);
}

const stylesDts = `// Generated by scripts/postbuild.mjs. Ambient declaration so strict-tsconfig
// consumers can \`import "@elvix.is/sdk/styles.css"\` without writing their own
// globals.d.ts shim. The CSS itself is the same file Tailwind compiled into
// dist/styles.css — this only teaches TypeScript that the import resolves.
declare module "@elvix.is/sdk/styles.css";
`;
writeFileSync("dist/styles.css.d.ts", stylesDts);
console.log("postbuild: wrote dist/styles.css.d.ts");
